version: '3'

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add:
      - SYS_PTRACE
    restart: unless-stopped
    ports:
      - '1433:1433'
    environment:
      MSSQL_SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '2500:25'
    volumes:
      # This is where smtp4dev stores the database..
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=localhost

volumes:
  smtp4dev-data:
